[tasks.start-all]
description = "Start Docker Compose"
run = "docker compose -f docker/docker-compose.yml up -d"

[tasks.flink-logs]
description = "Start Docker Compose"
run = "docker compose -f docker/docker-compose.yml logs taskmanager"

[tasks."open:kafka-ui"]
description = "Open Kafka UI"
run = "open http://localhost:8080"

[tasks."open:flink-ui"]
description = "Open Flink UI"
run = "open http://localhost:8081"

[tasks."flink:build"]
description = "Build Flink Jobs JAR"
run = "cd flink-jobs && mvn clean package"

[tasks.flink-customer-analytics]
description = "Build and Run Customer Analytics Flink Job"
run = "cd flink-jobs && mvn clean package exec:java -Dexec.mainClass=flinkfintechpoc.jobs.CustomerAnalyticsJob"

[tasks.run-flink-word-count-job]
depends = ["flink:build"]
description = "Build and Run Word Count Flink Job"
run = "flink run -c flinkfintechpoc.jobs.WordCountJob flink-jobs/target/flink-jobs-1.0-SNAPSHOT.jar"
