[tasks.start-all]
description = "Start Docker Compose"
run = "docker compose -f docker/docker-compose.yml up -d"

[tasks.kafka-ui]
description = "Open Kafka UI"
run = "open http://localhost:8080"

[tasks.flink-customer-analytics]
description = "Build and Run Customer Analytics Flink Job"
run = "cd flink-jobs && mvn clean package && cd .. && flink run flink-jobs/target/flink-jobs-1.0-SNAPSHOT.jar"
