# add deps: java, maven, flink, lein

[tasks."docker:start:all"]
description = "Start all required components (Kafka, Flink, Postgres, Kafka UI)"
run = "docker compose -f docker/docker-compose.yml up -d"

[tasks."flink:logs"]
description = "Show Flink Logs"
run = "docker compose -f docker/docker-compose.yml logs taskmanager --follow"

[tasks."open:kafka-ui"]
description = "Open Kafka UI"
run = "open http://localhost:8080"

[tasks."open:flink-ui"]
description = "Open Flink UI"
run = "open http://localhost:8081"

[tasks."flink:build"]
description = "Build Flink Jobs JAR"
run = "cd flink-jobs && mvn clean package"

[tasks."flink:run:customer-analytics"]
depends = ["flink:build"]
description = "Build and Run Customer Analytics Flink Job"
run = "flink run -c flinkfintechpoc.jobs.CustomerAnalyticsJob flink-jobs/target/flink-jobs-1.0-SNAPSHOT.jar"

[tasks."flink:run:word-count"]
depends = ["flink:build"]
description = "Build and Run Word Count Flink Job"
run = "flink run -c flinkfintechpoc.jobs.WordCountJob flink-jobs/target/flink-jobs-1.0-SNAPSHOT.jar"

[tasks."flink:run:customer-debezium"]
depends = ["flink:jobs:cancel", "flink:build"]
description = "Build and Run Word Count Flink Job"
run = "flink run -c flinkfintechpoc.jobs.CustomerDebeziumJob flink-jobs/target/flink-jobs-1.0-SNAPSHOT.jar"

[tasks."flink:jobs:cancel"]
description = "Cancel all running Flink jobs"
run = "flink list -r | grep -Eo '[0-9a-f]{32}' | xargs -n 1 flink cancel"

[tasks."connectors:register"]
description = "Register Kafka Connectors"
run = "cd app && lein run -m flinkfintechpoc.connectors/register-connectors!"

[tasks."postgres:connect"]
description = "Connect to PostgreSQL using psql"
run = "docker exec -it $(docker compose -f docker/docker-compose.yml ps -q postgres) psql -U postgres -d outbox_demo"
