# Flink Fintech POC - Essential Tasks Only

# =============================================================================
# DOCKER INFRASTRUCTURE
# =============================================================================

[tasks."docker:start"]
description = "Start all Docker containers"
run = "docker compose -f docker/docker-compose.yml up -d"

[tasks."docker:stop"]
description = "Stop all Docker containers"
run = "docker compose -f docker/docker-compose.yml down"

[tasks."docker:logs"]
description = "Show logs from all containers"
run = "docker compose -f docker/docker-compose.yml logs --follow"

[tasks."docker:ps"]
description = "Show status of all containers"
run = "docker compose -f docker/docker-compose.yml ps"

# =============================================================================
# WEB INTERFACES
# =============================================================================

[tasks."open:kafka-ui"]
description = "Open Kafka UI (port 8080)"
run = "start http://localhost:8080"

[tasks."open:flink-ui"]
description = "Open Flink UI (port 8081)"
run = "start http://localhost:8081"

[tasks."open:pgadmin"]
description = "Open pgAdmin (port 8082)"
run = "start http://localhost:8082"

[tasks."open:grafana"]
description = "Open Grafana (port 3000)"
run = "start http://localhost:3000"


# =============================================================================
# FLINK JOBS
# =============================================================================

[tasks."flink:build"]
description = "Build Flink JAR package"
run = "cd flink-jobs && mvn clean package"

[tasks."flink:run"]
description = "Run main analytics job"
run = "docker compose -f docker/docker-compose.yml exec -it jobmanager flink run -c flinkfintechpoc.jobs.FintechAnalyticsJob /opt/flink/jobs/flink-jobs-1.0-SNAPSHOT.jar"



# =============================================================================
# QUICK START
# =============================================================================

[tasks."start:all"]
description = "Complete startup: start services, build and run Flink job"
depends = ["docker:start", "flink:build", "flink:run"]
run = "echo 'All services started! Check: Kafka UI (8080), Flink UI (8081), pgAdmin (8082)'"

# =============================================================================
# PYTHON APP
# =============================================================================

[tasks."python:container:stop"]
description = "Gracefully stop producer inside container (without stopping container)"
run = "docker compose -f docker/docker-compose.yml stop fintech-python-app"

[tasks."python:producer:start"]
description = "Start producer inside container"
run = "docker compose -f docker/docker-compose.yml exec -d fintech-python-app python main.py start-producer --rate 10 --num-customers 50"

[tasks."python:container:start"]
description = "Start only the Python app container"
run = "docker compose -f docker/docker-compose.yml up -d fintech-python-app"

[tasks."python:producer:term"]
description = "Send SIGTERM to container main process (no shell quoting)"
run = "docker compose -f docker/docker-compose.yml kill -s SIGTERM fintech-python-app"


[tasks."docker:volume:clean"]
description = "Clean up all Docker volumes"
run = "docker volume rm $(docker volume ls -q)"