# Flink Fintech POC - Essential Tasks Only

# =============================================================================
# DOCKER INFRASTRUCTURE
# =============================================================================

[tasks."docker:start"]
description = "Start all Docker containers"
run = "docker compose -f docker/docker-compose.yml up -d"

[tasks."docker:stop"]
description = "Stop all Docker containers"
run = "docker compose -f docker/docker-compose.yml down"

[tasks."docker:logs"]
description = "Show logs from all containers"
run = "docker compose -f docker/docker-compose.yml logs --follow"

[tasks."docker:ps"]
description = "Show status of all containers"
run = "docker compose -f docker/docker-compose.yml ps"

# =============================================================================
# WEB INTERFACES
# =============================================================================

[tasks."open:kafka-ui"]
description = "Open Kafka UI (port 8080)"
run = "start http://localhost:8080"

[tasks."open:flink-ui"]
description = "Open Flink UI (port 8081)"
run = "start http://localhost:8081"

[tasks."open:pgadmin"]
description = "Open pgAdmin (port 8082)"
run = "start http://localhost:8082"

# =============================================================================
# PYTHON APP
# =============================================================================

[tasks."python:start"]
description = "Start real-time data producer"
run = "cd app-python && python main.py run-all --rate 5 --num-customers 50"

[tasks."python:setup"]
description = "Setup Python app and connectors"
run = "cd app-python && python main.py setup-connectors"

# =============================================================================
# FLINK JOBS
# =============================================================================

[tasks."flink:build"]
description = "Build Flink JAR package"
run = "cd flink-jobs && mvn clean package"

[tasks."flink:run"]
description = "Run main analytics job"
run = "docker compose -f docker/docker-compose.yml exec -it jobmanager flink run -c flinkfintechpoc.jobs.FintechAnalyticsJob /opt/flink/jobs/flink-jobs-1.0-SNAPSHOT.jar"

[tasks."flink:jobs"]
description = "List running Flink jobs"
run = "docker compose -f docker/docker-compose.yml exec jobmanager flink list"

# =============================================================================
# DATABASE
# =============================================================================

[tasks."postgres:connect"]
description = "Connect to PostgreSQL"
run = "docker compose -f docker/docker-compose.yml exec -it postgres psql -U postgres -d fintech_demo"

# =============================================================================
# QUICK START
# =============================================================================

[tasks."start:all"]
description = "Complete startup: start services, setup app, run Flink job"
depends = ["docker:start", "python:setup", "python:start", "flink:build", "flink:run"]
run = "echo 'All services started! Check: Kafka UI (8080), Flink UI (8081), pgAdmin (8082)'"

[tasks."status"]
description = "Show project status"
run = "echo '=== DOCKER ===' && docker compose -f docker/docker-compose.yml ps && echo '=== FLINK JOBS ===' && docker compose -f docker/docker-compose.yml exec jobmanager flink list"