# add deps: java, maven, flink, lein

[tasks.start-all]
description = "Start Docker Compose"
run = "docker compose -f docker/docker-compose.yml up -d"

[tasks.flink-logs]
description = "Start Docker Compose"
run = "docker compose -f docker/docker-compose.yml logs taskmanager --follow"

[tasks."open:kafka-ui"]
description = "Open Kafka UI"
run = "open http://localhost:8080"

[tasks."open:flink-ui"]
description = "Open Flink UI"
run = "open http://localhost:8081"

[tasks."flink:build"]
description = "Build Flink Jobs JAR"
run = "cd flink-jobs && mvn clean package"

[tasks."flink:run:customer-analytics"]
depends = ["flink:build"]
description = "Build and Run Customer Analytics Flink Job"
run = "flink run -c flinkfintechpoc.jobs.CustomerAnalyticsJob flink-jobs/target/flink-jobs-1.0-SNAPSHOT.jar"

[tasks."flink:run:word-count"]
depends = ["flink:build"]
description = "Build and Run Word Count Flink Job"
run = "flink run -c flinkfintechpoc.jobs.WordCountJob flink-jobs/target/flink-jobs-1.0-SNAPSHOT.jar"

[tasks."register-connectors"]
description = "Register Kafka Connectors"
run = "cd app && lein run -m flinkfintechpoc.connectors/register-connectors!"
