# add deps: java, maven, flink, lein

[tasks."docker:start:all"]
description = "Start all required components (Kafka, Flink, Postgres, Kafka UI)"
run = "docker compose -f docker/docker-compose.yml up -d"

[tasks."flink:logs"]
description = "Show Flink Logs"
run = "docker compose -f docker/docker-compose.yml logs taskmanager --follow"

[tasks."open:kafka-ui"]
description = "Open Kafka UI"
run = "open http://localhost:8080"

[tasks."open:flink-ui"]
description = "Open Flink UI"
run = "open http://localhost:8081"

[tasks."flink:build"]
description = "Build Flink Jobs JAR"
run = "cd flink-jobs && mvn clean package"

[tasks."flink:run:customer-analytics"]
depends = ["flink:build"]
description = "Build and Run Customer Analytics Flink Job"
run = "flink run -c flinkfintechpoc.jobs.CustomerAnalyticsJob flink-jobs/target/flink-jobs-1.0-SNAPSHOT.jar"

[tasks."flink:run:word-count"]
depends = ["flink:build"]
description = "Build and Run Word Count Flink Job"
run = "flink run -c flinkfintechpoc.jobs.WordCountJob flink-jobs/target/flink-jobs-1.0-SNAPSHOT.jar"

[tasks."flink:run:customer-debezium"]
depends = ["flink:build"]
description = "Build and Run Word Count Flink Job"
run = "flink run -c flinkfintechpoc.jobs.CustomerDebeziumJob flink-jobs/target/flink-jobs-1.0-SNAPSHOT.jar"

[tasks."flink:jobs:cancel"]
description = "Cancel all running Flink jobs"
run = '''
for job in $(flink list -r | awk '/Running/ {print $4}'); do
  echo "Cancelling job: $job"
  flink cancel "$job"
done
'''

[tasks."connectors:register"]
description = "Register Kafka Connectors"
run = "cd app && lein run -m flinkfintechpoc.connectors/register-connectors!"
